/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ActividadesSeminarioSOIndexRouteImport } from './routes/ActividadesSeminarioSO/index'
import { Route as ActividadesSeminarioSOActividad14IndexRouteImport } from './routes/ActividadesSeminarioSO/actividad14/index'
import { Route as ActividadesSeminarioSOActividad13IndexRouteImport } from './routes/ActividadesSeminarioSO/actividad13/index'
import { Route as ActividadesSeminarioSOActividad12IndexRouteImport } from './routes/ActividadesSeminarioSO/actividad12/index'
import { Route as ActividadesSeminarioSOActividad11IndexRouteImport } from './routes/ActividadesSeminarioSO/actividad11/index'
import { Route as ActividadesSeminarioSOActividad11ThunderingHerdRouteImport } from './routes/ActividadesSeminarioSO/actividad11/thundering-herd'
import { Route as ActividadesSeminarioSOActividad11StarvationRouteImport } from './routes/ActividadesSeminarioSO/actividad11/starvation'
import { Route as ActividadesSeminarioSOActividad11PriorityInversionRouteImport } from './routes/ActividadesSeminarioSO/actividad11/priority-inversion'
import { Route as ActividadesSeminarioSOActividad11MemoryConsistencyRouteImport } from './routes/ActividadesSeminarioSO/actividad11/memory-consistency'
import { Route as ActividadesSeminarioSOActividad11LostWakeupRouteImport } from './routes/ActividadesSeminarioSO/actividad11/lost-wakeup'
import { Route as ActividadesSeminarioSOActividad11LivelockRouteImport } from './routes/ActividadesSeminarioSO/actividad11/livelock'
import { Route as ActividadesSeminarioSOActividad11LecturaEscrituraRouteImport } from './routes/ActividadesSeminarioSO/actividad11/lectura-escritura'
import { Route as ActividadesSeminarioSOActividad11FalseSharingRouteImport } from './routes/ActividadesSeminarioSO/actividad11/false-sharing'
import { Route as ActividadesSeminarioSOActividad11EventosRouteImport } from './routes/ActividadesSeminarioSO/actividad11/eventos'
import { Route as ActividadesSeminarioSOActividad11DeadlockRouteImport } from './routes/ActividadesSeminarioSO/actividad11/deadlock'
import { Route as ActividadesSeminarioSOActividad11ConvoyingRouteImport } from './routes/ActividadesSeminarioSO/actividad11/convoying'
import { Route as ActividadesSeminarioSOActividad11ContencionRecursosRouteImport } from './routes/ActividadesSeminarioSO/actividad11/contencion-recursos'
import { Route as ActividadesSeminarioSOActividad11CondicionCarreraRouteImport } from './routes/ActividadesSeminarioSO/actividad11/condicion-carrera'
import { Route as ActividadesSeminarioSOActividad11BloqueosInnecesariosRouteImport } from './routes/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios'
import { Route as ActividadesSeminarioSOActividad11AbaRouteImport } from './routes/ActividadesSeminarioSO/actividad11/aba'

const ActividadesSeminarioSOIndexRoute =
  ActividadesSeminarioSOIndexRouteImport.update({
    id: '/ActividadesSeminarioSO/',
    path: '/ActividadesSeminarioSO/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad14IndexRoute =
  ActividadesSeminarioSOActividad14IndexRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad14/',
    path: '/ActividadesSeminarioSO/actividad14/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad13IndexRoute =
  ActividadesSeminarioSOActividad13IndexRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad13/',
    path: '/ActividadesSeminarioSO/actividad13/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad12IndexRoute =
  ActividadesSeminarioSOActividad12IndexRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad12/',
    path: '/ActividadesSeminarioSO/actividad12/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11IndexRoute =
  ActividadesSeminarioSOActividad11IndexRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/',
    path: '/ActividadesSeminarioSO/actividad11/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11ThunderingHerdRoute =
  ActividadesSeminarioSOActividad11ThunderingHerdRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/thundering-herd',
    path: '/ActividadesSeminarioSO/actividad11/thundering-herd',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11StarvationRoute =
  ActividadesSeminarioSOActividad11StarvationRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/starvation',
    path: '/ActividadesSeminarioSO/actividad11/starvation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11PriorityInversionRoute =
  ActividadesSeminarioSOActividad11PriorityInversionRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/priority-inversion',
    path: '/ActividadesSeminarioSO/actividad11/priority-inversion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11MemoryConsistencyRoute =
  ActividadesSeminarioSOActividad11MemoryConsistencyRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/memory-consistency',
    path: '/ActividadesSeminarioSO/actividad11/memory-consistency',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11LostWakeupRoute =
  ActividadesSeminarioSOActividad11LostWakeupRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/lost-wakeup',
    path: '/ActividadesSeminarioSO/actividad11/lost-wakeup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11LivelockRoute =
  ActividadesSeminarioSOActividad11LivelockRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/livelock',
    path: '/ActividadesSeminarioSO/actividad11/livelock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11LecturaEscrituraRoute =
  ActividadesSeminarioSOActividad11LecturaEscrituraRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/lectura-escritura',
    path: '/ActividadesSeminarioSO/actividad11/lectura-escritura',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11FalseSharingRoute =
  ActividadesSeminarioSOActividad11FalseSharingRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/false-sharing',
    path: '/ActividadesSeminarioSO/actividad11/false-sharing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11EventosRoute =
  ActividadesSeminarioSOActividad11EventosRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/eventos',
    path: '/ActividadesSeminarioSO/actividad11/eventos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11DeadlockRoute =
  ActividadesSeminarioSOActividad11DeadlockRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/deadlock',
    path: '/ActividadesSeminarioSO/actividad11/deadlock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11ConvoyingRoute =
  ActividadesSeminarioSOActividad11ConvoyingRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/convoying',
    path: '/ActividadesSeminarioSO/actividad11/convoying',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11ContencionRecursosRoute =
  ActividadesSeminarioSOActividad11ContencionRecursosRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/contencion-recursos',
    path: '/ActividadesSeminarioSO/actividad11/contencion-recursos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11CondicionCarreraRoute =
  ActividadesSeminarioSOActividad11CondicionCarreraRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/condicion-carrera',
    path: '/ActividadesSeminarioSO/actividad11/condicion-carrera',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11BloqueosInnecesariosRoute =
  ActividadesSeminarioSOActividad11BloqueosInnecesariosRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios',
    path: '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActividadesSeminarioSOActividad11AbaRoute =
  ActividadesSeminarioSOActividad11AbaRouteImport.update({
    id: '/ActividadesSeminarioSO/actividad11/aba',
    path: '/ActividadesSeminarioSO/actividad11/aba',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/ActividadesSeminarioSO': typeof ActividadesSeminarioSOIndexRoute
  '/ActividadesSeminarioSO/actividad11/aba': typeof ActividadesSeminarioSOActividad11AbaRoute
  '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios': typeof ActividadesSeminarioSOActividad11BloqueosInnecesariosRoute
  '/ActividadesSeminarioSO/actividad11/condicion-carrera': typeof ActividadesSeminarioSOActividad11CondicionCarreraRoute
  '/ActividadesSeminarioSO/actividad11/contencion-recursos': typeof ActividadesSeminarioSOActividad11ContencionRecursosRoute
  '/ActividadesSeminarioSO/actividad11/convoying': typeof ActividadesSeminarioSOActividad11ConvoyingRoute
  '/ActividadesSeminarioSO/actividad11/deadlock': typeof ActividadesSeminarioSOActividad11DeadlockRoute
  '/ActividadesSeminarioSO/actividad11/eventos': typeof ActividadesSeminarioSOActividad11EventosRoute
  '/ActividadesSeminarioSO/actividad11/false-sharing': typeof ActividadesSeminarioSOActividad11FalseSharingRoute
  '/ActividadesSeminarioSO/actividad11/lectura-escritura': typeof ActividadesSeminarioSOActividad11LecturaEscrituraRoute
  '/ActividadesSeminarioSO/actividad11/livelock': typeof ActividadesSeminarioSOActividad11LivelockRoute
  '/ActividadesSeminarioSO/actividad11/lost-wakeup': typeof ActividadesSeminarioSOActividad11LostWakeupRoute
  '/ActividadesSeminarioSO/actividad11/memory-consistency': typeof ActividadesSeminarioSOActividad11MemoryConsistencyRoute
  '/ActividadesSeminarioSO/actividad11/priority-inversion': typeof ActividadesSeminarioSOActividad11PriorityInversionRoute
  '/ActividadesSeminarioSO/actividad11/starvation': typeof ActividadesSeminarioSOActividad11StarvationRoute
  '/ActividadesSeminarioSO/actividad11/thundering-herd': typeof ActividadesSeminarioSOActividad11ThunderingHerdRoute
  '/ActividadesSeminarioSO/actividad11': typeof ActividadesSeminarioSOActividad11IndexRoute
  '/ActividadesSeminarioSO/actividad12': typeof ActividadesSeminarioSOActividad12IndexRoute
  '/ActividadesSeminarioSO/actividad13': typeof ActividadesSeminarioSOActividad13IndexRoute
  '/ActividadesSeminarioSO/actividad14': typeof ActividadesSeminarioSOActividad14IndexRoute
}
export interface FileRoutesByTo {
  '/ActividadesSeminarioSO': typeof ActividadesSeminarioSOIndexRoute
  '/ActividadesSeminarioSO/actividad11/aba': typeof ActividadesSeminarioSOActividad11AbaRoute
  '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios': typeof ActividadesSeminarioSOActividad11BloqueosInnecesariosRoute
  '/ActividadesSeminarioSO/actividad11/condicion-carrera': typeof ActividadesSeminarioSOActividad11CondicionCarreraRoute
  '/ActividadesSeminarioSO/actividad11/contencion-recursos': typeof ActividadesSeminarioSOActividad11ContencionRecursosRoute
  '/ActividadesSeminarioSO/actividad11/convoying': typeof ActividadesSeminarioSOActividad11ConvoyingRoute
  '/ActividadesSeminarioSO/actividad11/deadlock': typeof ActividadesSeminarioSOActividad11DeadlockRoute
  '/ActividadesSeminarioSO/actividad11/eventos': typeof ActividadesSeminarioSOActividad11EventosRoute
  '/ActividadesSeminarioSO/actividad11/false-sharing': typeof ActividadesSeminarioSOActividad11FalseSharingRoute
  '/ActividadesSeminarioSO/actividad11/lectura-escritura': typeof ActividadesSeminarioSOActividad11LecturaEscrituraRoute
  '/ActividadesSeminarioSO/actividad11/livelock': typeof ActividadesSeminarioSOActividad11LivelockRoute
  '/ActividadesSeminarioSO/actividad11/lost-wakeup': typeof ActividadesSeminarioSOActividad11LostWakeupRoute
  '/ActividadesSeminarioSO/actividad11/memory-consistency': typeof ActividadesSeminarioSOActividad11MemoryConsistencyRoute
  '/ActividadesSeminarioSO/actividad11/priority-inversion': typeof ActividadesSeminarioSOActividad11PriorityInversionRoute
  '/ActividadesSeminarioSO/actividad11/starvation': typeof ActividadesSeminarioSOActividad11StarvationRoute
  '/ActividadesSeminarioSO/actividad11/thundering-herd': typeof ActividadesSeminarioSOActividad11ThunderingHerdRoute
  '/ActividadesSeminarioSO/actividad11': typeof ActividadesSeminarioSOActividad11IndexRoute
  '/ActividadesSeminarioSO/actividad12': typeof ActividadesSeminarioSOActividad12IndexRoute
  '/ActividadesSeminarioSO/actividad13': typeof ActividadesSeminarioSOActividad13IndexRoute
  '/ActividadesSeminarioSO/actividad14': typeof ActividadesSeminarioSOActividad14IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ActividadesSeminarioSO/': typeof ActividadesSeminarioSOIndexRoute
  '/ActividadesSeminarioSO/actividad11/aba': typeof ActividadesSeminarioSOActividad11AbaRoute
  '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios': typeof ActividadesSeminarioSOActividad11BloqueosInnecesariosRoute
  '/ActividadesSeminarioSO/actividad11/condicion-carrera': typeof ActividadesSeminarioSOActividad11CondicionCarreraRoute
  '/ActividadesSeminarioSO/actividad11/contencion-recursos': typeof ActividadesSeminarioSOActividad11ContencionRecursosRoute
  '/ActividadesSeminarioSO/actividad11/convoying': typeof ActividadesSeminarioSOActividad11ConvoyingRoute
  '/ActividadesSeminarioSO/actividad11/deadlock': typeof ActividadesSeminarioSOActividad11DeadlockRoute
  '/ActividadesSeminarioSO/actividad11/eventos': typeof ActividadesSeminarioSOActividad11EventosRoute
  '/ActividadesSeminarioSO/actividad11/false-sharing': typeof ActividadesSeminarioSOActividad11FalseSharingRoute
  '/ActividadesSeminarioSO/actividad11/lectura-escritura': typeof ActividadesSeminarioSOActividad11LecturaEscrituraRoute
  '/ActividadesSeminarioSO/actividad11/livelock': typeof ActividadesSeminarioSOActividad11LivelockRoute
  '/ActividadesSeminarioSO/actividad11/lost-wakeup': typeof ActividadesSeminarioSOActividad11LostWakeupRoute
  '/ActividadesSeminarioSO/actividad11/memory-consistency': typeof ActividadesSeminarioSOActividad11MemoryConsistencyRoute
  '/ActividadesSeminarioSO/actividad11/priority-inversion': typeof ActividadesSeminarioSOActividad11PriorityInversionRoute
  '/ActividadesSeminarioSO/actividad11/starvation': typeof ActividadesSeminarioSOActividad11StarvationRoute
  '/ActividadesSeminarioSO/actividad11/thundering-herd': typeof ActividadesSeminarioSOActividad11ThunderingHerdRoute
  '/ActividadesSeminarioSO/actividad11/': typeof ActividadesSeminarioSOActividad11IndexRoute
  '/ActividadesSeminarioSO/actividad12/': typeof ActividadesSeminarioSOActividad12IndexRoute
  '/ActividadesSeminarioSO/actividad13/': typeof ActividadesSeminarioSOActividad13IndexRoute
  '/ActividadesSeminarioSO/actividad14/': typeof ActividadesSeminarioSOActividad14IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ActividadesSeminarioSO'
    | '/ActividadesSeminarioSO/actividad11/aba'
    | '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios'
    | '/ActividadesSeminarioSO/actividad11/condicion-carrera'
    | '/ActividadesSeminarioSO/actividad11/contencion-recursos'
    | '/ActividadesSeminarioSO/actividad11/convoying'
    | '/ActividadesSeminarioSO/actividad11/deadlock'
    | '/ActividadesSeminarioSO/actividad11/eventos'
    | '/ActividadesSeminarioSO/actividad11/false-sharing'
    | '/ActividadesSeminarioSO/actividad11/lectura-escritura'
    | '/ActividadesSeminarioSO/actividad11/livelock'
    | '/ActividadesSeminarioSO/actividad11/lost-wakeup'
    | '/ActividadesSeminarioSO/actividad11/memory-consistency'
    | '/ActividadesSeminarioSO/actividad11/priority-inversion'
    | '/ActividadesSeminarioSO/actividad11/starvation'
    | '/ActividadesSeminarioSO/actividad11/thundering-herd'
    | '/ActividadesSeminarioSO/actividad11'
    | '/ActividadesSeminarioSO/actividad12'
    | '/ActividadesSeminarioSO/actividad13'
    | '/ActividadesSeminarioSO/actividad14'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ActividadesSeminarioSO'
    | '/ActividadesSeminarioSO/actividad11/aba'
    | '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios'
    | '/ActividadesSeminarioSO/actividad11/condicion-carrera'
    | '/ActividadesSeminarioSO/actividad11/contencion-recursos'
    | '/ActividadesSeminarioSO/actividad11/convoying'
    | '/ActividadesSeminarioSO/actividad11/deadlock'
    | '/ActividadesSeminarioSO/actividad11/eventos'
    | '/ActividadesSeminarioSO/actividad11/false-sharing'
    | '/ActividadesSeminarioSO/actividad11/lectura-escritura'
    | '/ActividadesSeminarioSO/actividad11/livelock'
    | '/ActividadesSeminarioSO/actividad11/lost-wakeup'
    | '/ActividadesSeminarioSO/actividad11/memory-consistency'
    | '/ActividadesSeminarioSO/actividad11/priority-inversion'
    | '/ActividadesSeminarioSO/actividad11/starvation'
    | '/ActividadesSeminarioSO/actividad11/thundering-herd'
    | '/ActividadesSeminarioSO/actividad11'
    | '/ActividadesSeminarioSO/actividad12'
    | '/ActividadesSeminarioSO/actividad13'
    | '/ActividadesSeminarioSO/actividad14'
  id:
    | '__root__'
    | '/ActividadesSeminarioSO/'
    | '/ActividadesSeminarioSO/actividad11/aba'
    | '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios'
    | '/ActividadesSeminarioSO/actividad11/condicion-carrera'
    | '/ActividadesSeminarioSO/actividad11/contencion-recursos'
    | '/ActividadesSeminarioSO/actividad11/convoying'
    | '/ActividadesSeminarioSO/actividad11/deadlock'
    | '/ActividadesSeminarioSO/actividad11/eventos'
    | '/ActividadesSeminarioSO/actividad11/false-sharing'
    | '/ActividadesSeminarioSO/actividad11/lectura-escritura'
    | '/ActividadesSeminarioSO/actividad11/livelock'
    | '/ActividadesSeminarioSO/actividad11/lost-wakeup'
    | '/ActividadesSeminarioSO/actividad11/memory-consistency'
    | '/ActividadesSeminarioSO/actividad11/priority-inversion'
    | '/ActividadesSeminarioSO/actividad11/starvation'
    | '/ActividadesSeminarioSO/actividad11/thundering-herd'
    | '/ActividadesSeminarioSO/actividad11/'
    | '/ActividadesSeminarioSO/actividad12/'
    | '/ActividadesSeminarioSO/actividad13/'
    | '/ActividadesSeminarioSO/actividad14/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ActividadesSeminarioSOIndexRoute: typeof ActividadesSeminarioSOIndexRoute
  ActividadesSeminarioSOActividad11AbaRoute: typeof ActividadesSeminarioSOActividad11AbaRoute
  ActividadesSeminarioSOActividad11BloqueosInnecesariosRoute: typeof ActividadesSeminarioSOActividad11BloqueosInnecesariosRoute
  ActividadesSeminarioSOActividad11CondicionCarreraRoute: typeof ActividadesSeminarioSOActividad11CondicionCarreraRoute
  ActividadesSeminarioSOActividad11ContencionRecursosRoute: typeof ActividadesSeminarioSOActividad11ContencionRecursosRoute
  ActividadesSeminarioSOActividad11ConvoyingRoute: typeof ActividadesSeminarioSOActividad11ConvoyingRoute
  ActividadesSeminarioSOActividad11DeadlockRoute: typeof ActividadesSeminarioSOActividad11DeadlockRoute
  ActividadesSeminarioSOActividad11EventosRoute: typeof ActividadesSeminarioSOActividad11EventosRoute
  ActividadesSeminarioSOActividad11FalseSharingRoute: typeof ActividadesSeminarioSOActividad11FalseSharingRoute
  ActividadesSeminarioSOActividad11LecturaEscrituraRoute: typeof ActividadesSeminarioSOActividad11LecturaEscrituraRoute
  ActividadesSeminarioSOActividad11LivelockRoute: typeof ActividadesSeminarioSOActividad11LivelockRoute
  ActividadesSeminarioSOActividad11LostWakeupRoute: typeof ActividadesSeminarioSOActividad11LostWakeupRoute
  ActividadesSeminarioSOActividad11MemoryConsistencyRoute: typeof ActividadesSeminarioSOActividad11MemoryConsistencyRoute
  ActividadesSeminarioSOActividad11PriorityInversionRoute: typeof ActividadesSeminarioSOActividad11PriorityInversionRoute
  ActividadesSeminarioSOActividad11StarvationRoute: typeof ActividadesSeminarioSOActividad11StarvationRoute
  ActividadesSeminarioSOActividad11ThunderingHerdRoute: typeof ActividadesSeminarioSOActividad11ThunderingHerdRoute
  ActividadesSeminarioSOActividad11IndexRoute: typeof ActividadesSeminarioSOActividad11IndexRoute
  ActividadesSeminarioSOActividad12IndexRoute: typeof ActividadesSeminarioSOActividad12IndexRoute
  ActividadesSeminarioSOActividad13IndexRoute: typeof ActividadesSeminarioSOActividad13IndexRoute
  ActividadesSeminarioSOActividad14IndexRoute: typeof ActividadesSeminarioSOActividad14IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ActividadesSeminarioSO/': {
      id: '/ActividadesSeminarioSO/'
      path: '/ActividadesSeminarioSO'
      fullPath: '/ActividadesSeminarioSO'
      preLoaderRoute: typeof ActividadesSeminarioSOIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad14/': {
      id: '/ActividadesSeminarioSO/actividad14/'
      path: '/ActividadesSeminarioSO/actividad14'
      fullPath: '/ActividadesSeminarioSO/actividad14'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad14IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad13/': {
      id: '/ActividadesSeminarioSO/actividad13/'
      path: '/ActividadesSeminarioSO/actividad13'
      fullPath: '/ActividadesSeminarioSO/actividad13'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad13IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad12/': {
      id: '/ActividadesSeminarioSO/actividad12/'
      path: '/ActividadesSeminarioSO/actividad12'
      fullPath: '/ActividadesSeminarioSO/actividad12'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad12IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/': {
      id: '/ActividadesSeminarioSO/actividad11/'
      path: '/ActividadesSeminarioSO/actividad11'
      fullPath: '/ActividadesSeminarioSO/actividad11'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/thundering-herd': {
      id: '/ActividadesSeminarioSO/actividad11/thundering-herd'
      path: '/ActividadesSeminarioSO/actividad11/thundering-herd'
      fullPath: '/ActividadesSeminarioSO/actividad11/thundering-herd'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11ThunderingHerdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/starvation': {
      id: '/ActividadesSeminarioSO/actividad11/starvation'
      path: '/ActividadesSeminarioSO/actividad11/starvation'
      fullPath: '/ActividadesSeminarioSO/actividad11/starvation'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11StarvationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/priority-inversion': {
      id: '/ActividadesSeminarioSO/actividad11/priority-inversion'
      path: '/ActividadesSeminarioSO/actividad11/priority-inversion'
      fullPath: '/ActividadesSeminarioSO/actividad11/priority-inversion'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11PriorityInversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/memory-consistency': {
      id: '/ActividadesSeminarioSO/actividad11/memory-consistency'
      path: '/ActividadesSeminarioSO/actividad11/memory-consistency'
      fullPath: '/ActividadesSeminarioSO/actividad11/memory-consistency'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11MemoryConsistencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/lost-wakeup': {
      id: '/ActividadesSeminarioSO/actividad11/lost-wakeup'
      path: '/ActividadesSeminarioSO/actividad11/lost-wakeup'
      fullPath: '/ActividadesSeminarioSO/actividad11/lost-wakeup'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11LostWakeupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/livelock': {
      id: '/ActividadesSeminarioSO/actividad11/livelock'
      path: '/ActividadesSeminarioSO/actividad11/livelock'
      fullPath: '/ActividadesSeminarioSO/actividad11/livelock'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11LivelockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/lectura-escritura': {
      id: '/ActividadesSeminarioSO/actividad11/lectura-escritura'
      path: '/ActividadesSeminarioSO/actividad11/lectura-escritura'
      fullPath: '/ActividadesSeminarioSO/actividad11/lectura-escritura'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11LecturaEscrituraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/false-sharing': {
      id: '/ActividadesSeminarioSO/actividad11/false-sharing'
      path: '/ActividadesSeminarioSO/actividad11/false-sharing'
      fullPath: '/ActividadesSeminarioSO/actividad11/false-sharing'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11FalseSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/eventos': {
      id: '/ActividadesSeminarioSO/actividad11/eventos'
      path: '/ActividadesSeminarioSO/actividad11/eventos'
      fullPath: '/ActividadesSeminarioSO/actividad11/eventos'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/deadlock': {
      id: '/ActividadesSeminarioSO/actividad11/deadlock'
      path: '/ActividadesSeminarioSO/actividad11/deadlock'
      fullPath: '/ActividadesSeminarioSO/actividad11/deadlock'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11DeadlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/convoying': {
      id: '/ActividadesSeminarioSO/actividad11/convoying'
      path: '/ActividadesSeminarioSO/actividad11/convoying'
      fullPath: '/ActividadesSeminarioSO/actividad11/convoying'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11ConvoyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/contencion-recursos': {
      id: '/ActividadesSeminarioSO/actividad11/contencion-recursos'
      path: '/ActividadesSeminarioSO/actividad11/contencion-recursos'
      fullPath: '/ActividadesSeminarioSO/actividad11/contencion-recursos'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11ContencionRecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/condicion-carrera': {
      id: '/ActividadesSeminarioSO/actividad11/condicion-carrera'
      path: '/ActividadesSeminarioSO/actividad11/condicion-carrera'
      fullPath: '/ActividadesSeminarioSO/actividad11/condicion-carrera'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11CondicionCarreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios': {
      id: '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios'
      path: '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios'
      fullPath: '/ActividadesSeminarioSO/actividad11/bloqueos-innecesarios'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11BloqueosInnecesariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ActividadesSeminarioSO/actividad11/aba': {
      id: '/ActividadesSeminarioSO/actividad11/aba'
      path: '/ActividadesSeminarioSO/actividad11/aba'
      fullPath: '/ActividadesSeminarioSO/actividad11/aba'
      preLoaderRoute: typeof ActividadesSeminarioSOActividad11AbaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ActividadesSeminarioSOIndexRoute: ActividadesSeminarioSOIndexRoute,
  ActividadesSeminarioSOActividad11AbaRoute:
    ActividadesSeminarioSOActividad11AbaRoute,
  ActividadesSeminarioSOActividad11BloqueosInnecesariosRoute:
    ActividadesSeminarioSOActividad11BloqueosInnecesariosRoute,
  ActividadesSeminarioSOActividad11CondicionCarreraRoute:
    ActividadesSeminarioSOActividad11CondicionCarreraRoute,
  ActividadesSeminarioSOActividad11ContencionRecursosRoute:
    ActividadesSeminarioSOActividad11ContencionRecursosRoute,
  ActividadesSeminarioSOActividad11ConvoyingRoute:
    ActividadesSeminarioSOActividad11ConvoyingRoute,
  ActividadesSeminarioSOActividad11DeadlockRoute:
    ActividadesSeminarioSOActividad11DeadlockRoute,
  ActividadesSeminarioSOActividad11EventosRoute:
    ActividadesSeminarioSOActividad11EventosRoute,
  ActividadesSeminarioSOActividad11FalseSharingRoute:
    ActividadesSeminarioSOActividad11FalseSharingRoute,
  ActividadesSeminarioSOActividad11LecturaEscrituraRoute:
    ActividadesSeminarioSOActividad11LecturaEscrituraRoute,
  ActividadesSeminarioSOActividad11LivelockRoute:
    ActividadesSeminarioSOActividad11LivelockRoute,
  ActividadesSeminarioSOActividad11LostWakeupRoute:
    ActividadesSeminarioSOActividad11LostWakeupRoute,
  ActividadesSeminarioSOActividad11MemoryConsistencyRoute:
    ActividadesSeminarioSOActividad11MemoryConsistencyRoute,
  ActividadesSeminarioSOActividad11PriorityInversionRoute:
    ActividadesSeminarioSOActividad11PriorityInversionRoute,
  ActividadesSeminarioSOActividad11StarvationRoute:
    ActividadesSeminarioSOActividad11StarvationRoute,
  ActividadesSeminarioSOActividad11ThunderingHerdRoute:
    ActividadesSeminarioSOActividad11ThunderingHerdRoute,
  ActividadesSeminarioSOActividad11IndexRoute:
    ActividadesSeminarioSOActividad11IndexRoute,
  ActividadesSeminarioSOActividad12IndexRoute:
    ActividadesSeminarioSOActividad12IndexRoute,
  ActividadesSeminarioSOActividad13IndexRoute:
    ActividadesSeminarioSOActividad13IndexRoute,
  ActividadesSeminarioSOActividad14IndexRoute:
    ActividadesSeminarioSOActividad14IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
