/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Actividad14RouteImport } from './routes/actividad14'
import { Route as Actividad13RouteImport } from './routes/actividad13'
import { Route as Actividad12RouteImport } from './routes/actividad12'
import { Route as Actividad11RouteImport } from './routes/actividad11'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Actividad11IndexRouteImport } from './routes/actividad11/index'
import { Route as Actividad11StarvationRouteImport } from './routes/actividad11/starvation'
import { Route as Actividad11DeadlockRouteImport } from './routes/actividad11/deadlock'
import { Route as Actividad11CondicionCarreraRouteImport } from './routes/actividad11/condicion-carrera'

const Actividad14Route = Actividad14RouteImport.update({
  id: '/actividad14',
  path: '/actividad14',
  getParentRoute: () => rootRouteImport,
} as any)
const Actividad13Route = Actividad13RouteImport.update({
  id: '/actividad13',
  path: '/actividad13',
  getParentRoute: () => rootRouteImport,
} as any)
const Actividad12Route = Actividad12RouteImport.update({
  id: '/actividad12',
  path: '/actividad12',
  getParentRoute: () => rootRouteImport,
} as any)
const Actividad11Route = Actividad11RouteImport.update({
  id: '/actividad11',
  path: '/actividad11',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Actividad11IndexRoute = Actividad11IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Actividad11Route,
} as any)
const Actividad11StarvationRoute = Actividad11StarvationRouteImport.update({
  id: '/starvation',
  path: '/starvation',
  getParentRoute: () => Actividad11Route,
} as any)
const Actividad11DeadlockRoute = Actividad11DeadlockRouteImport.update({
  id: '/deadlock',
  path: '/deadlock',
  getParentRoute: () => Actividad11Route,
} as any)
const Actividad11CondicionCarreraRoute =
  Actividad11CondicionCarreraRouteImport.update({
    id: '/condicion-carrera',
    path: '/condicion-carrera',
    getParentRoute: () => Actividad11Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividad11': typeof Actividad11RouteWithChildren
  '/actividad12': typeof Actividad12Route
  '/actividad13': typeof Actividad13Route
  '/actividad14': typeof Actividad14Route
  '/actividad11/condicion-carrera': typeof Actividad11CondicionCarreraRoute
  '/actividad11/deadlock': typeof Actividad11DeadlockRoute
  '/actividad11/starvation': typeof Actividad11StarvationRoute
  '/actividad11/': typeof Actividad11IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividad12': typeof Actividad12Route
  '/actividad13': typeof Actividad13Route
  '/actividad14': typeof Actividad14Route
  '/actividad11/condicion-carrera': typeof Actividad11CondicionCarreraRoute
  '/actividad11/deadlock': typeof Actividad11DeadlockRoute
  '/actividad11/starvation': typeof Actividad11StarvationRoute
  '/actividad11': typeof Actividad11IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividad11': typeof Actividad11RouteWithChildren
  '/actividad12': typeof Actividad12Route
  '/actividad13': typeof Actividad13Route
  '/actividad14': typeof Actividad14Route
  '/actividad11/condicion-carrera': typeof Actividad11CondicionCarreraRoute
  '/actividad11/deadlock': typeof Actividad11DeadlockRoute
  '/actividad11/starvation': typeof Actividad11StarvationRoute
  '/actividad11/': typeof Actividad11IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividad11'
    | '/actividad12'
    | '/actividad13'
    | '/actividad14'
    | '/actividad11/condicion-carrera'
    | '/actividad11/deadlock'
    | '/actividad11/starvation'
    | '/actividad11/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividad12'
    | '/actividad13'
    | '/actividad14'
    | '/actividad11/condicion-carrera'
    | '/actividad11/deadlock'
    | '/actividad11/starvation'
    | '/actividad11'
  id:
    | '__root__'
    | '/'
    | '/actividad11'
    | '/actividad12'
    | '/actividad13'
    | '/actividad14'
    | '/actividad11/condicion-carrera'
    | '/actividad11/deadlock'
    | '/actividad11/starvation'
    | '/actividad11/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Actividad11Route: typeof Actividad11RouteWithChildren
  Actividad12Route: typeof Actividad12Route
  Actividad13Route: typeof Actividad13Route
  Actividad14Route: typeof Actividad14Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/actividad14': {
      id: '/actividad14'
      path: '/actividad14'
      fullPath: '/actividad14'
      preLoaderRoute: typeof Actividad14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad13': {
      id: '/actividad13'
      path: '/actividad13'
      fullPath: '/actividad13'
      preLoaderRoute: typeof Actividad13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad12': {
      id: '/actividad12'
      path: '/actividad12'
      fullPath: '/actividad12'
      preLoaderRoute: typeof Actividad12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad11': {
      id: '/actividad11'
      path: '/actividad11'
      fullPath: '/actividad11'
      preLoaderRoute: typeof Actividad11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad11/': {
      id: '/actividad11/'
      path: '/'
      fullPath: '/actividad11/'
      preLoaderRoute: typeof Actividad11IndexRouteImport
      parentRoute: typeof Actividad11Route
    }
    '/actividad11/starvation': {
      id: '/actividad11/starvation'
      path: '/starvation'
      fullPath: '/actividad11/starvation'
      preLoaderRoute: typeof Actividad11StarvationRouteImport
      parentRoute: typeof Actividad11Route
    }
    '/actividad11/deadlock': {
      id: '/actividad11/deadlock'
      path: '/deadlock'
      fullPath: '/actividad11/deadlock'
      preLoaderRoute: typeof Actividad11DeadlockRouteImport
      parentRoute: typeof Actividad11Route
    }
    '/actividad11/condicion-carrera': {
      id: '/actividad11/condicion-carrera'
      path: '/condicion-carrera'
      fullPath: '/actividad11/condicion-carrera'
      preLoaderRoute: typeof Actividad11CondicionCarreraRouteImport
      parentRoute: typeof Actividad11Route
    }
  }
}

interface Actividad11RouteChildren {
  Actividad11CondicionCarreraRoute: typeof Actividad11CondicionCarreraRoute
  Actividad11DeadlockRoute: typeof Actividad11DeadlockRoute
  Actividad11StarvationRoute: typeof Actividad11StarvationRoute
  Actividad11IndexRoute: typeof Actividad11IndexRoute
}

const Actividad11RouteChildren: Actividad11RouteChildren = {
  Actividad11CondicionCarreraRoute: Actividad11CondicionCarreraRoute,
  Actividad11DeadlockRoute: Actividad11DeadlockRoute,
  Actividad11StarvationRoute: Actividad11StarvationRoute,
  Actividad11IndexRoute: Actividad11IndexRoute,
}

const Actividad11RouteWithChildren = Actividad11Route._addFileChildren(
  Actividad11RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Actividad11Route: Actividad11RouteWithChildren,
  Actividad12Route: Actividad12Route,
  Actividad13Route: Actividad13Route,
  Actividad14Route: Actividad14Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
